
import React, { useState, useEffect } from 'react';
import { PlannerResponse, PlanPhase, Project, GitHubSkill } from '../types';
import { COMPONENTS } from './ComponentRegistry';
import { me, logout, listProjects, createProject, updateProject, getSkills } from '../lib/api';

interface BuildStudioProps {
  initialTab?: 'architect' | 'library' | 'handoff';
  onExit: () => void;
}

const DEFAULT_STACK = 'Next.js 15, TypeScript, Tailwind CSS, Prisma';

function buildPlanMarkdown(plan: PlannerResponse): string {
  const lines: string[] = [
    `# ${plan.projectName}`,
    ``,
    `> Architecture plan generated by ShipFast. Feed each phase prompt to your coding agent in order.`,
    ``,
    `## Overview`,
    ``,
    plan.overview,
    ``,
    `## Stack`,
    ``,
    plan.stack,
    ``,
    `## Build phases (in order)`,
    ``,
  ];
  plan.phases.forEach((p, i) => {
    lines.push(`### Phase ${i + 1}: ${p.title}`, ``, p.goal, ``, `**Prompt for your coding agent:**`, ``, '```', p.prompt, '```', ``, `**Files touched:**`, ``);
    p.files.forEach((f) => lines.push(`- \`${f.path}\` — ${f.purpose}`));
    lines.push(``, `**Acceptance criteria:**`, ``);
    p.acceptance.forEach((a) => lines.push(`- [ ] ${a}`));
    lines.push(``);
  });
  lines.push(`## Data model`, ``);
  plan.dataModel.forEach((d) => lines.push(`- **${d.entity}**: ${d.fields}`));
  lines.push(``, `## API contract`, ``);
  plan.apiContract.forEach((a) => lines.push(`- \`${a.method} ${a.path}\` — ${a.purpose}`));
  lines.push(``, `## UI elements to use`, ``);
  plan.elements.forEach((e) => lines.push(`- ${e}`));
  lines.push(``, `## Agent skills to look up`, ``);
  plan.skills.forEach((s) => lines.push(`- **${s.name}** — ${s.reason}`));
  lines.push(``, `## Risks`, ``);
  plan.risks.forEach((r) => lines.push(`- ${r}`));
  lines.push(``, `## Launch checklist`, ``);
  plan.launchChecklist.forEach((c) => lines.push(`- [ ] ${c}`));
  lines.push(``);
  return lines.join('\n');
}

const BuildStudio: React.FC<BuildStudioProps> = ({ initialTab = 'architect', onExit }) => {
  const [activeTab, setActiveTab] = useState<'architect' | 'library' | 'handoff'>(initialTab);
  const [prompt, setPrompt] = useState('');
  const [stack, setStack] = useState(DEFAULT_STACK);
  const [selectedElements, setSelectedElements] = useState<string[]>([]);
  const [plan, setPlan] = useState<PlannerResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [isProfileModalOpen, setIsProfileModalOpen] = useState(false);
  const [user, setUser] = useState<any>(null);
  const [expandedPhase, setExpandedPhase] = useState<number | null>(0);

  const [projects, setProjects] = useState<Project[]>([]);
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null);

  const [skillResults, setSkillResults] = useState<Record<string, GitHubSkill[]>>({});
  const [skillsLoading, setSkillsLoading] = useState<string | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // Initial Load from the Cloudflare API (D1)
  useEffect(() => {
    const fetchInitialData = async () => {
      setIsSyncing(true);
      const authUser = await me();
      setUser(authUser);
      if (authUser) {
        try {
          const rows = await listProjects();
          setProjects(rows as Project[]);
        } catch (err) {
          console.error("[Studio] Projects fetch error:", err);
        }
      }
      setIsSyncing(false);
    };
    fetchInitialData();
  }, []);

  const handleSignOut = async () => {
    await logout();
    onExit();
  };

  const copyText = async (key: string, text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const generatePlan = async () => {
    if (!prompt.trim() || !user) return;
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/proxy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, stack, elements: selectedElements }),
      });
      if (!response.ok) throw new Error(`Server error: ${response.status}`);

      const geminiResponse = await response.json();
      const rawText = geminiResponse.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!rawText) throw new Error("Could not extract a plan from the AI response.");

      const parsed = JSON.parse(rawText.trim()) as PlannerResponse;
      if (!parsed.phases || !Array.isArray(parsed.phases)) throw new Error("AI returned an invalid plan. Try again.");
      setPlan(parsed);
      setExpandedPhase(0);
      setSkillResults({});

      const created = await createProject({
        name: parsed.projectName,
        stack: parsed.stack || stack,
        status: 'planned',
        scaffold: parsed,
      });

      setProjects(prev => [created as Project, ...prev]);
      setActiveProjectId(created.id);
      setPrompt('');
    } catch (err: any) {
      setError(err.message || "Failed to generate plan.");
      console.error("[Studio] Error generating plan:", err);
    } finally {
      setIsLoading(false);
    }
  };

  const lookupSkill = async (skillName: string) => {
    setSkillsLoading(skillName);
    try {
      const results = await getSkills(skillName);
      setSkillResults(prev => ({ ...prev, [skillName]: results }));
    } catch (err) {
      console.error("[Studio] Skills lookup error:", err);
    } finally {
      setSkillsLoading(null);
    }
  };

  const openProject = (p: Project) => {
    if (p.scaffold) {
      setPlan(p.scaffold);
      setExpandedPhase(0);
      setSkillResults({});
    }
    setActiveProjectId(p.id);
  };

  const markExported = async () => {
    if (!activeProjectId) return;
    try {
      await updateProject(activeProjectId, { status: 'exported', lastDeployed: new Date().toISOString() });
      setProjects(prev => prev.map(p => p.id === activeProjectId ? { ...p, status: 'exported' as const, lastDeployed: new Date().toISOString() } : p));
    } catch (err) {
      console.error("[Studio] Mark exported error:", err);
    }
  };

  const downloadMarkdown = () => {
    if (!plan) return;
    const blob = new Blob([buildPlanMarkdown(plan)], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${plan.projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-plan.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const toggleElement = (name: string) => {
    setSelectedElements(prev => prev.includes(name) ? prev.filter(e => e !== name) : [...prev, name]);
  };

  const statusBadge = (status: string) => {
    const styles: Record<string, string> = {
      draft: 'bg-slate-50 text-slate-400 border-slate-100',
      planned: 'bg-blue-50 text-blue-600 border-blue-100',
      exported: 'bg-green-50 text-green-600 border-green-100',
    };
    return <span className={`text-[8px] font-black uppercase px-2 py-0.5 rounded border ${styles[status] || styles.draft}`}>{status}</span>;
  };

  const renderPhase = (phase: PlanPhase, i: number) => {
    const open = expandedPhase === i;
    const key = `phase-${i}`;
    return (
      <div key={i} className="border border-slate-200 rounded-3xl overflow-hidden bg-white">
        <button onClick={() => setExpandedPhase(open ? null : i)} className="w-full text-left p-5 flex items-center gap-4">
          <span className="w-8 h-8 rounded-full bg-black text-white text-xs font-black flex items-center justify-center shrink-0">{i + 1}</span>
          <span className="flex-1">
            <span className="block font-bold text-black">{phase.title}</span>
            <span className="block text-xs text-slate-500 mt-0.5">{phase.goal}</span>
          </span>
          <span className="text-slate-300 text-xl">{open ? '−' : '+'}</span>
        </button>
        {open && (
          <div className="px-5 pb-5 space-y-4">
            <div className="bg-slate-900 rounded-2xl p-5 relative">
              <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">Prompt for your coding agent</p>
              <pre className="whitespace-pre-wrap font-mono text-[11px] leading-relaxed text-slate-200">{phase.prompt}</pre>
              <button onClick={() => copyText(key, phase.prompt)} className="mt-3 text-[10px] font-black text-slate-400 hover:text-white uppercase tracking-widest">
                {copiedKey === key ? 'Copied!' : 'Copy prompt'}
              </button>
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Files touched (map only, no code)</p>
              {phase.files.map((f, j) => (
                <p key={j} className="text-xs text-slate-600 font-mono py-1 border-b border-slate-50">{f.path} <span className="text-slate-400 font-sans">— {f.purpose}</span></p>
              ))}
            </div>
            <div>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Done when</p>
              {phase.acceptance.map((a, j) => (
                <p key={j} className="text-xs text-slate-600 py-0.5">☐ {a}</p>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex h-screen w-full bg-[#FCFCFD] overflow-hidden animate-in fade-in duration-500">
      {/* Profile Modal Overlay */}
      {isProfileModalOpen && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-md animate-in fade-in duration-300" onClick={() => setIsProfileModalOpen(false)}></div>
          <div
            className="relative w-full max-w-lg bg-white rounded-[3rem] shadow-2xl p-10 lg:p-12 overflow-hidden animate-in zoom-in-95 fade-in duration-300 z-10"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="absolute top-0 right-0 w-64 h-64 bg-slate-50 rounded-full -mr-32 -mt-32 blur-3xl opacity-50 -z-10"></div>

            <button
              onClick={() => setIsProfileModalOpen(false)}
              className="absolute top-8 right-8 p-3 rounded-full hover:bg-slate-50 transition-colors z-50 group"
              aria-label="Close profile modal"
            >
              <svg className="w-6 h-6 text-slate-400 group-hover:text-black transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>

            <div className="relative z-10 flex flex-col items-center">
              <div className="w-24 h-24 rounded-[2rem] bg-black p-1 shadow-2xl mb-6 flex items-center justify-center overflow-hidden">
                <span className="text-3xl font-black text-white">{user?.email?.charAt(0).toUpperCase()}</span>
              </div>

              <h3 className="text-2xl font-black text-black tracking-tight mb-1">{user?.name || 'Anonymous Builder'}</h3>
              <p className="text-sm text-slate-400 font-medium mb-8">{user?.email}</p>

              <div className="w-full space-y-4 mb-10">
                <div className="p-6 rounded-3xl bg-slate-50 border border-slate-100 flex items-center justify-between">
                  <div>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Current Plan</h4>
                    <p className="text-sm font-bold text-black">ShipFast Professional</p>
                  </div>
                  <span className="px-3 py-1 bg-black text-white text-[10px] font-black rounded-lg uppercase">Active</span>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="p-5 rounded-3xl border border-slate-100 flex flex-col items-center justify-center text-center">
                    <span className="text-xl font-black text-black mb-1">{projects.length}</span>
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Plans</span>
                  </div>
                  <div className="p-5 rounded-3xl border border-slate-100 flex flex-col items-center justify-center text-center">
                    <span className="text-xl font-black text-black mb-1">∞</span>
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">AI Tokens</span>
                  </div>
                </div>
              </div>

              <div className="w-full flex flex-col gap-3">
                <button
                  onClick={handleSignOut}
                  className="w-full py-4 text-red-500 hover:text-red-600 text-sm font-bold rounded-2xl transition-all"
                >
                  Sign Out Account
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {isSidebarOpen && <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-[60] lg:hidden" onClick={() => setIsSidebarOpen(false)} />}

      <aside className={`fixed inset-y-0 left-0 w-72 bg-white border-r border-slate-200 flex flex-col z-[70] transition-transform duration-300 lg:relative lg:translate-x-0 ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="p-6 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={onExit}>
            <div className="w-8 h-8 bg-black rounded-lg flex items-center justify-center shadow-lg"><svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div>
            <span className="font-bold text-black tracking-tight">Studio</span>
          </div>
          <button onClick={() => setIsSidebarOpen(false)} className="lg:hidden text-slate-400 hover:text-black transition-colors"><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button>
        </div>

        <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
          <h4 className="px-3 text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4 mt-2">Workspace</h4>
          {[
            { id: 'architect', label: 'Architect', icon: 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4' },
            { id: 'library', label: 'Elements', icon: 'M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z' },
            { id: 'handoff', label: 'Handoff', icon: 'M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12' }
          ].map(tab => (
            <button key={tab.id} onClick={() => { setActiveTab(tab.id as any); setIsSidebarOpen(false); }} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold transition-all ${activeTab === tab.id ? 'bg-black text-white shadow-lg' : 'text-slate-500 hover:bg-slate-50 hover:text-black'}`}>
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={tab.icon} /></svg>
              {tab.label}
            </button>
          ))}

          <div className="flex items-center justify-between px-3 mb-4 mt-8">
            <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Saved Plans</h4>
            {isSyncing && <div className="w-3 h-3 border-2 border-slate-200 border-t-slate-400 rounded-full animate-spin" />}
          </div>
          <div className="space-y-1">
            {projects.length === 0 && !isSyncing && <p className="px-3 text-[10px] text-slate-400 italic">No plans yet</p>}
            {projects.map(p => (
              <button key={p.id} onClick={() => {
                openProject(p);
                setIsSidebarOpen(false);
              }} className={`w-full text-left px-3 py-2 transition-colors truncate flex items-center justify-between gap-2 ${activeProjectId === p.id ? 'text-black font-bold bg-slate-50 rounded-lg' : 'text-slate-500 hover:text-black'}`}>
                <span className="text-xs font-medium truncate">{p.name}</span>
                {statusBadge(p.status)}
              </button>
            ))}
          </div>
        </nav>

        <div className="p-4 border-t border-slate-100 bg-slate-50/50">
          {user ? (
            <div className="flex items-center gap-3">
              <div
                onClick={() => setIsProfileModalOpen(true)}
                className="w-10 h-10 rounded-full bg-slate-200 border border-slate-300 overflow-hidden flex-shrink-0 cursor-pointer hover:ring-2 hover:ring-black transition-all"
              >
                <div className="w-full h-full flex items-center justify-center text-slate-500 text-xs font-bold uppercase">
                  {user.email?.charAt(0)}
                </div>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-bold text-black truncate">{user.name || 'Builder'}</p>
                <button onClick={() => setIsProfileModalOpen(true)} className="text-[10px] text-slate-500 hover:text-black transition-colors font-medium">My Profile</button>
              </div>
            </div>
          ) : (
            <div className="h-10 w-full animate-pulse bg-slate-200 rounded-xl" />
          )}
        </div>
      </aside>

      <main className="flex-1 flex flex-col relative overflow-hidden h-full">
        <header className="h-16 border-b border-slate-200 bg-white flex items-center justify-between px-4 lg:px-8 shrink-0">
          <div className="flex items-center gap-3">
            <button onClick={() => setIsSidebarOpen(true)} className="p-2 text-slate-500 lg:hidden"><svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg></button>
            <h2 className="text-xs lg:text-sm font-bold text-black uppercase tracking-wider">{activeTab === 'architect' ? 'Architecture Planner' : activeTab === 'library' ? 'UI Elements' : 'Agent Handoff'}</h2>
          </div>
          {activeProjectId && (
            <span className="text-[10px] text-slate-400 font-mono hidden sm:inline">{activeProjectId.substring(0, 8)}...</span>
          )}
        </header>

        <div className="flex-1 overflow-y-auto bg-white">
          <div className="max-w-4xl mx-auto p-6 lg:p-10 space-y-6">

            {activeTab === 'architect' && (
              <>
                {!plan ? (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-3xl lg:text-4xl font-extrabold text-black tracking-tight">Plan your build.</h3>
                      <p className="text-slate-500 text-lg mt-2">Describe your product. You get a phased plan with copy-paste prompts for your coding agent — no code, just the blueprint.</p>
                    </div>
                    <textarea
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      rows={4}
                      placeholder="Describe your SaaS concept (e.g. AI legal analyzer with document upload and Stripe billing)..."
                      className="w-full px-5 py-4 rounded-2xl border border-slate-200 text-black placeholder:text-slate-300 outline-none focus:border-black transition-colors"
                    />
                    <input
                      type="text"
                      value={stack}
                      onChange={(e) => setStack(e.target.value)}
                      placeholder="Target stack"
                      className="w-full px-5 py-4 rounded-2xl border border-slate-200 text-sm text-black placeholder:text-slate-300 outline-none focus:border-black transition-colors"
                    />
                    {selectedElements.length > 0 && (
                      <div className="flex flex-wrap gap-2">
                        {selectedElements.map(e => (
                          <span key={e} className="px-3 py-1 bg-black text-white text-xs font-bold rounded-full">{e}</span>
                        ))}
                        <button onClick={() => setActiveTab('library')} className="px-3 py-1 text-xs font-bold text-slate-500 hover:text-black">+ edit elements</button>
                      </div>
                    )}
                    {selectedElements.length === 0 && (
                      <button onClick={() => setActiveTab('library')} className="text-sm font-bold text-slate-500 hover:text-black">Pick UI elements from the library →</button>
                    )}
                    {error && <p className="text-red-500 text-sm font-bold bg-red-50 px-4 py-2 rounded-lg border border-red-100">{error}</p>}
                    <button onClick={generatePlan} disabled={isLoading || !prompt.trim()} className="px-8 py-4 bg-black text-white font-bold rounded-2xl shadow-lg hover:scale-[1.02] transition-all disabled:opacity-50">
                      {isLoading ? 'Planning architecture...' : 'Generate plan'}
                    </button>
                    {isLoading && (
                      <div className="flex items-center gap-3 text-sm font-bold text-black animate-pulse uppercase tracking-widest">
                        <div className="w-6 h-6 border-4 border-slate-100 border-t-black rounded-full animate-spin"></div>
                        Drafting phases...
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="space-y-6">
                    <div>
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Architecture plan</p>
                      <h3 className="text-3xl font-extrabold text-black tracking-tight">{plan.projectName}</h3>
                      <p className="text-slate-500 mt-2">{plan.overview}</p>
                      <p className="text-xs text-slate-400 font-mono mt-2">{plan.stack}</p>
                    </div>
                    <button onClick={() => { setPlan(null); setPrompt(''); }} className="text-sm font-bold text-slate-500 hover:text-black">← Start a new plan</button>

                    <div className="space-y-4">
                      <h4 className="text-sm font-black text-black uppercase tracking-widest">Build phases — feed these to your agent in order</h4>
                      {plan.phases.map((phase, i) => renderPhase(phase, i))}
                    </div>

                    <div className="grid sm:grid-cols-2 gap-4">
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Data model</p>
                        {plan.dataModel.map((d, j) => (
                          <p key={j} className="text-xs text-slate-600 py-1"><span className="font-bold text-black">{d.entity}:</span> {d.fields}</p>
                        ))}
                      </div>
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">API contract</p>
                        {plan.apiContract.map((a, j) => (
                          <p key={j} className="text-xs text-slate-600 font-mono py-1">{a.method} {a.path} <span className="font-sans text-slate-400">— {a.purpose}</span></p>
                        ))}
                      </div>
                    </div>

                    {plan.elements.length > 0 && (
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">UI elements to use</p>
                        <div className="flex flex-wrap gap-2">
                          {plan.elements.map((e, j) => (
                            <span key={j} className="px-3 py-1 bg-slate-100 text-xs font-bold text-black rounded-full">{e}</span>
                          ))}
                        </div>
                      </div>
                    )}

                    {plan.skills.length > 0 && (
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Agent skills to look up</p>
                        {plan.skills.map((s, j) => (
                          <div key={j} className="py-2 border-b border-slate-50 last:border-0">
                            <p className="text-sm font-bold text-black">{s.name}</p>
                            <p className="text-xs text-slate-500">{s.reason}</p>
                            <button onClick={() => lookupSkill(s.name)} className="text-[10px] font-black text-blue-600 uppercase tracking-widest hover:underline mt-1">
                              {skillsLoading === s.name ? 'Searching GitHub...' : 'Find on GitHub'}
                            </button>
                            {(skillResults[s.name] || []).map((g) => (
                              <a key={g.repo} href={g.url} target="_blank" rel="noopener noreferrer" className="block text-xs mt-1 hover:underline">
                                <span className="font-mono font-bold">★{g.stars} {g.repo}</span>
                                <span className="text-slate-500"> — {g.description}</span>
                              </a>
                            ))}
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="grid sm:grid-cols-2 gap-4">
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Risks</p>
                        {plan.risks.map((r, j) => (
                          <p key={j} className="text-xs text-slate-600 py-0.5">⚠ {r}</p>
                        ))}
                      </div>
                      <div className="border border-slate-200 rounded-3xl p-5">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Launch checklist</p>
                        {plan.launchChecklist.map((c, j) => (
                          <p key={j} className="text-xs text-slate-600 py-0.5">☐ {c}</p>
                        ))}
                      </div>
                    </div>

                    <button onClick={() => setActiveTab('handoff')} className="px-8 py-4 bg-black text-white font-bold rounded-2xl shadow-lg hover:scale-[1.02] transition-all">
                      Go to handoff →
                    </button>
                  </div>
                )}
              </>
            )}

            {activeTab === 'library' && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-3xl font-extrabold text-black tracking-tight">UI elements.</h3>
                  <p className="text-slate-500 mt-2">Select the elements your build should use. They get baked into the plan and the handoff doc.</p>
                </div>
                <div className="grid sm:grid-cols-2 gap-4">
                  {COMPONENTS.map(c => {
                    const selected = selectedElements.includes(c.name);
                    return (
                      <button key={c.id} onClick={() => toggleElement(c.name)} className={`text-left p-5 rounded-3xl border transition-all ${selected ? 'border-black bg-slate-50 shadow-lg' : 'border-slate-200 bg-white hover:border-slate-300'}`}>
                        <div className="flex items-center justify-between mb-2">
                          <p className="font-bold text-black">{c.name}</p>
                          <span className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${selected ? 'bg-black border-black text-white text-xs' : 'border-slate-200'}`}>{selected ? '✓' : ''}</span>
                        </div>
                        <p className="text-xs text-slate-500">{c.description}</p>
                        <div className="mt-3 p-4 bg-white border border-slate-100 rounded-2xl flex items-center justify-center min-h-[80px]">{c.preview}</div>
                      </button>
                    );
                  })}
                </div>
                {selectedElements.length > 0 && (
                  <button onClick={() => setActiveTab('architect')} className="px-8 py-4 bg-black text-white font-bold rounded-2xl shadow-lg hover:scale-[1.02] transition-all">
                    Use {selectedElements.length} element{selectedElements.length > 1 ? 's' : ''} in plan →
                  </button>
                )}
              </div>
            )}

            {activeTab === 'handoff' && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-3xl font-extrabold text-black tracking-tight">Agent handoff.</h3>
                  <p className="text-slate-500 mt-2">The full plan as one markdown doc. Copy it or download it, then paste it into your coding agent.</p>
                </div>
                {!plan ? (
                  <div className="border-2 border-dashed border-slate-200 rounded-3xl p-10 text-center">
                    <p className="text-slate-400 font-medium mb-4">No plan loaded. Generate one or open a saved plan.</p>
                    <button onClick={() => setActiveTab('architect')} className="px-6 py-3 bg-black text-white text-sm font-bold rounded-xl">Go to Architect</button>
                  </div>
                ) : (
                  <>
                    <div className="flex flex-wrap gap-3">
                      <button onClick={() => copyText('full-plan', buildPlanMarkdown(plan))} className="px-6 py-3 bg-black text-white text-sm font-bold rounded-xl shadow-lg">
                        {copiedKey === 'full-plan' ? 'Copied!' : 'Copy full plan'}
                      </button>
                      <button onClick={downloadMarkdown} className="px-6 py-3 bg-slate-100 hover:bg-slate-200 text-black text-sm font-bold rounded-xl transition-all">
                        Download .md
                      </button>
                      <button onClick={markExported} className="px-6 py-3 text-sm font-bold text-slate-500 hover:text-black transition-colors">
                        Mark exported
                      </button>
                    </div>
                    <div className="bg-slate-900 rounded-3xl p-6 lg:p-8 overflow-x-auto">
                      <pre className="whitespace-pre-wrap font-mono text-[11px] leading-relaxed text-slate-300">{buildPlanMarkdown(plan)}</pre>
                    </div>
                  </>
                )}
              </div>
            )}

          </div>
        </div>
      </main>
    </div>
  );
};

export default BuildStudio;
